### ISSUE TITLE
It's not working on pull_request event

### ISSUE THREAD

**Issue by brenoalvs** [varunsridharan/action-wp-pot-generator#2]
**Describe the bug**
It retrieves an error when trying to push the POT file to the repository when running in the `pull_request` context.

**To Reproduce**
1. Create a workflow file with the event `pull_request`
2. Open a pull request to the desired branch and see the build fails.

```yml
name: Generate POT

on:
  pull_request:
    branches:
      - test-pr

jobs:
  i18n:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate POT file
      uses: varunsridharan/action-wp-pot-generator@1.1
      with:
        save_path: './languages'
        item_slug: 'plugin-slug'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**
The build should pass and with the new POT file generated and committed.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A
